### PR TITLE
3.2   tablas

### PR DESCRIPTION
**Pull request by mctuliomontoya**
This pull request creates the following screens & components:
- Log creation components: this are used to create new logs. we expect that, in the future, will be modified to create requests to backend.
- Buttons: created to direct the user to it's corresponding log-creation screen.
- Log screens depending on users: created different log screens depending on the user type

This pull request creates a lot of styled components to use in the future.

### CODE REVIEW

**Review by NovoxMx — APPROVED** [review]
Aprobado

**Comment by NovoxMx** [comment]
Aprovaddo

**Comment by NovoxMx** [comment]
Aprovado

**Review by Jaza2401 — APPROVED** [review]
LGTM

**Pull request merged**
